name: pizza-ci

on:
  push:
  pull_request:

jobs:
  localstack-terraform:
    runs-on: ubuntu-latest

    services:
      localstack:
        image: localstack/localstack:latest
        ports:
          - 4566:4566
        env:
          SERVICES: apigateway,lambda,dynamodb,s3,iam,logs,sts,cloudwatch
          AWS_DEFAULT_REGION: us-east-1
        options: >-
          --health-cmd="curl -s http://localhost:4566/_localstack/health || exit 1"
          --health-interval=5s
          --health-timeout=2s
          --health-retries=60

    env:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: us-east-1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-venv zip graphviz jq

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Wait for LocalStack
        run: |
          for i in {1..60}; do
            curl -s http://localhost:4566/_localstack/health >/dev/null && exit 0
            sleep 2
          done
          echo "LocalStack did not become healthy in time" >&2
          exit 1

      - name: Build Lambda
        run: make lambda-build

      - name: Terraform init
        run: make tf-init

      - name: Terraform plan
        run: make tf-plan

      - name: Terraform apply
        run: make tf-apply

      - name: Smoke test (pizza stack)
        run: make smoke

      - name: Terraform destroy
        if: always()
        run: make tf-destroy
